[2021-04-05 05:10:28,203] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks.bash3 2021-04-02T00:00:00+00:00 [queued]>
[2021-04-05 05:10:28,347] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks.bash3 2021-04-02T00:00:00+00:00 [queued]>
[2021-04-05 05:10:28,347] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:10:28,347] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-04-05 05:10:28,347] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:10:28,447] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): processing_tasks.bash3> on 2021-04-02T00:00:00+00:00
[2021-04-05 05:10:28,454] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_tasks.bash3', '2021-04-02T00:00:00+00:00', '--job-id', '279', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp43e5s3s4']
[2021-04-05 05:10:28,454] {standard_task_runner.py:76} INFO - Job 279: Subtask processing_tasks.bash3
[2021-04-05 05:10:28,492] {standard_task_runner.py:51} INFO - Started process 2370 to run task
[2021-04-05 05:10:29,183] {logging_mixin.py:103} INFO - Running <TaskInstance: parallel_dag.processing_tasks.bash3 2021-04-02T00:00:00+00:00 [running]> on host airflowvm
[2021-04-05 05:10:29,828] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_tasks.bash3
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T00:00:00+00:00
[2021-04-05 05:10:29,849] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-05 05:10:29,850] {bash.py:158} INFO - Running command: sleep 3
[2021-04-05 05:10:29,917] {bash.py:169} INFO - Output:
[2021-04-05 05:10:32,943] {bash.py:177} INFO - Command exited with return code 0
[2021-04-05 05:10:33,428] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=processing_tasks.bash3, execution_date=20210402T000000, start_date=20210405T051028, end_date=20210405T051033
[2021-04-05 05:10:33,991] {local_task_job.py:169} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-04-05 05:10:34,079] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-05 05:10:34,120] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 2370
[2021-04-05 05:10:34,184] {process_utils.py:61} INFO - Process psutil.Process(pid=2370, status='terminated', exitcode=0, started='05:10:27') (2370) terminated with exit code 0
[2021-04-05 05:10:34,185] {local_task_job.py:118} INFO - Task exited with return code 0
